import {Inter} from "next/font/google";
import "./.././../admin-global.css";
import * as React from "react";
import Header from "@/app/admin/components/modules/Header/Header";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Добавление набора",
    description: "Generated by create next app",
};

export default function AddSetLayout({children}) {

    return (
        <div>
        {children}
        </div>
    );
}
