import "./../admin-global.css";

export const metadata = {
    title: "Формы",
    description: "Generated by create next app",
};

export default function FormsLayout({children}) {
    return (
        <div>
        {children}

        </div>
    );
}
