import { Inter } from "next/font/google";
import "./admin.css";

//echo "# rat" >> README.md
// git init
// git add .
// git commit -m "first commit"
// git branch -M main
// git remote add origin https://github.com/Valentin679/rat.git
// git push -u origin main


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
